name: Swift Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  swift-format:
    runs-on: macos-15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '6.1'
    
    - name: Run swift format lint
      run: swift format lint -s -r .
